### ISSUE TITLE
Pls fix

### ISSUE THREAD

**Issue by JoKrastanov** [ktarneva/youConcert#2]
/* BDO fonts */
@import url("https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");

* {
  margin: 0;
  padding: 0;
}

div {
  font-family: "Poppins", sans-serif;
}

.button {
  padding: 0.313rem .875rem;
  border-radius: 0.313rem;
  height: .75rem;
  display: flex;
  justify-content: center;
  align-items: center;
  cursor: pointer;
  font-size: .825rem;
}

.red-button {
  color: white;
  background: #ed1a3b;
}

.gray-button {
  color: white;
  background: #e7e7e7;
}

.green-button {
  color: white;
  background: #218f8b;
}

.link-button {
  color: gray;
  height: 1.25rem;
  text-align: center;
  cursor: pointer;
}

.resolve-button {
  width: .75rem;
  height: .75rem;
  padding: 0.313rem;
  border-radius: 0.313rem;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  background: #218F8B;
}

.reportSize{
  height: 100vh;
}

**Comment by ktarneva** [comment]
how about no?
